name: Hello Python Script Workflow

on:
  workflow_dispatch:
    inputs:
      entity:
        description: "who to say hello to"
        required: true
      file:
        description: "file to create/edit"
        required: true
        

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check if file already exists
        id: file_exists
        uses: thebinaryfelix/check-file-existence-action@2.0.0
        with:
          files: ${{ github.event.inputs.file }}

      - name: Set up Python
        if: steps.file_exists.outputs.exists == 'true'
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Edit file
        if: steps.file_exists.outputs.exists == 'true'
        run: |
          pip install ruamel.yaml
          python hello.py ${{ github.event.inputs.entity }}