name: Hello Python Script Workflow

on:
  workflow_dispatch:
    inputs:
      entity:
        description: "who to say hello to"
        required: true
      file:
        description: "file to create/edit"
        required: true

env:
  FILE: ${{ github.event.inputs.file }}
  ENTITY: ${{ github.event.inputs.entity }}
        

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check if file already exists
        id: file_exists
        uses: thebinaryfelix/check-file-existence-action@2.0.0
        with:
          files: $FILE

      - name: Set up Python
        if: steps.file_exists.outputs.exists == 'true'
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Install
        if: steps.file_exists.outputs.exists == 'true'
        run: pip install ruamel.yaml
      
      - name: Run Python script
        if: steps.file_exists.outputs.exists == 'true'
        run: python hello.py $ENTITY