name: Hello Python Script Workflow

on:
  workflow_dispatch:
    inputs:
      entity:
        description: "who to say hello to"
        required: true  
        

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7 
        with:
          python-version: '3.13'

      - name: Install
        run: pip install ruamel.yaml
      
      - name: Run Python script
        run: python hello.py